### ISSUE TITLE
Reliability loss converges to 0.5 instead of 0.

### ISSUE THREAD

**Issue by MarviB16** [naver/r2d2#16]
Hello,

I am using your proposed framework to match historical and present satellite imagery. However, the reliability loss does not converge to 0, but to 0.5. Which results in an AP of 0 and a reliability score of 0. I would guess that is due to the initial AP being too low.

Did you experience any similar behavior while testing? Or do you have an idea why this could happen?

**Comment by jrevaud** [comment]
Hi

No, I've never seen this behavior. As you said, this is most likely due to the fact the the matching problem is harder on your data than on our data.

What you can do is change the value of \kappa in the reliability loss. This represents the threshold above which an AP is considered to be "good" -- by default it is equal to 0.5 (see  `ReliabilityLoss(base=0.5)`).
So you can try to lower it to 0.1 or even below, and see if it helps for the convergence.

Another solution would be to 
 1- step 1: train without the reliability (ie using `PixelAPLoss()` instead of `ReliabilityLoss()`)
 2- step 2: continue training with the reliability

**Comment by Chjx395** [comment]
> Hello,
> 
> I am using your proposed framework to match historical and present satellite imagery. However, the reliability loss does not converge to 0, but to 0.5. Which results in an AP of 0 and a reliability score of 0. I would guess that is due to the initial AP being too low.
> 
> Did you experience any similar behavior while testing? Or do you have an idea why this could happen?

Hi there,

I have the same problem. Have you solved the problem?
